Installation request to Dooplugins
doofinder/doofinder-magento2 pull request #299
Opened 2024-01-23 10:43 UTC by eduardogomez97

Required by: https://github.com/doofinder/dooplugins/issues/99

2024-01-23 10:50 UTC, sofia-doofinder commented on Controller/Adminhtml/Integration/CreateStore.php
> +        return
Edu, creo que esto de los callback no lo puedes quitar porque es para la gestión después para saber si la indexación ha ido bien o no

2024-01-23 10:52 UTC, sofia-doofinder commented on Controller/Adminhtml/Integration/CreateStore.php
> +        return
vale que lo que has hecho es moverlo, entonces esta función se podría borrar no? aunque le voy a dar una vuelta porque se me hace raro como has cambiado el tema del callback

2024-01-23 11:03 UTC, sofia-doofinder commented on Controller/Adminhtml/Integration/CreateStore.php
> +        return
vale Edu, o mueves el código aquí y que se llame al a función o borra la función

2024-01-23 11:26 UTC, eduardogomez97 commented on Controller/Adminhtml/Integration/CreateStore.php
> +        return
Sí, voy a borrar la función. Me ha dado cuenta del error al intentar hacer la prueba porque se me había pasado borrarlo. En cuanto finalice el resto de pruebas subo un commit con todo lo que vea!

El caso es que el proceso de instalación de dooplugins espera el callback por cada search_engine por eso la adaptación.

2024-01-23 12:36 UTC, ivan-doofinder approved these changes

2024-01-24 08:11 UTC, davidmolinacano approved these changes
Good job! Let's test it together! :raised_hands:

2024-01-24 08:28 UTC, davidmolinacano requested changes

2024-01-24 08:28 UTC, davidmolinacano commented on Controller/Adminhtml/Integration/CreateStore.php
> +        $store_id = $store->getId();
I think the variable `$store` is undefined at this point

2024-01-24 11:02 UTC, davidmolinacano approved these changes
This change works flawlessly, good job! :handshake:

2024-01-24 11:14 UTC, davidmolinacano reviewed
Just a minimal change

2024-01-24 11:14 UTC, davidmolinacano commented on Controller/Adminhtml/Integration/CreateStore.php
> +    function get_primary_site_url_in_se($search_engines, $primary_language) {
If this function is only used here, I would change it to private :smile: 
```suggestion
    private function get_primary_site_url_in_se($search_engines, $primary_language) {    
```

2024-01-24 11:16 UTC, sofia-doofinder approved these changes

2024-01-24 12:17 UTC, ivan-doofinder approved these changes

2024-01-24 14:45 UTC, merged