Compatible with Magento 2.4.7, as backward compatibility has been lost in the Magento\Catalog\Model\ProductRepository class
doofinder/doofinder-magento2 pull request #318
Opened 2024-05-10 04:40 UTC by TuVanDev

As of Magento 2.4.7, backward compatibility has been lost in the Magento\Catalog\Model\ProductRepository class. This pull request aims to fix this issue.

Check the issue page in the Magento repo for reference: https://github.com/magento/magento2/issues/38669.

---
The changes made in this pull request are as follows:
- Updated version
- Replaced the `__construct()` method with multiple methods that utilize ObjectManager to instantiate the necessary instances. This change was made to prevent errors during code complication:
> Incompatible argument type: Required type: \Magento\Catalog\Api\Data\ProductSearchResultsInterfaceFactory. Actual type: \Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper; File: 
> /app/app/code/Doofinder/Feed/Model/ProductRepository.php
>  
- Additional improvements were made as follows:
    - Fixed typos 
    - Removed the unused property, `$stockRegistry`.
    - Replaced the `$excludedCustomAttributes` property with a constant. Using a class constant for a fixed value that will be used within a method helps to clearly define and identify the value as a constant for that class. It also ensures that the value remains consistent and cannot be changed or modified within the class methods.
    - Removed nullable parameter type from the `$attributes` param, as it must be of type array since it is used as the second param in an `array_merge()` [function](https://github.com/magento/magento2/blob/2.4.7/app/code/Magento/Catalog/Helper/Image.php#L190), which requires an array type.

2024-05-10 08:42 UTC, sofia-doofinder requested changes

2024-05-10 08:42 UTC, sofia-doofinder commented on Model/ProductRepository.php
> +        return $this->inventoryHelper;
```suggestion
        return $this->inventoryHelperFactory;
```

2024-05-10 08:54 UTC, davidmolinacano approved these changes
LGTM! :trophy: (Although we have to take into account @sofia-doofinder's correction)

2024-05-10 09:17 UTC, sofia-doofinder approved these changes

2024-05-13 10:20 UTC, Aitor-Corrales approved these changes
Using the objectManager directly is not a good practice as it defeats the purpose of dependency injection. That being said, I'm guessing there is no other way to bypass the backwards compatibility issue of the 2.4.7 version. For the future, when this issue gets addressed, I would study going back to the usage of the constructor again, even tho this particular minor version would not work anymore, as Magento will probably decommend it.

2024-05-13 13:11 UTC, merged